### ISSUE TITLE
Bable VS NodeJS ES6

### ISSUE THREAD

**Issue by Saturate** [Saturate/polymerase#8]
Hi,

I'm considering if we want to use the newest features of ES6.
NodeJS has some of the features but for import statements ect.

Pros for Babel/Rollup:

- ES6 Syntax will make our code more readable
- Future safe
- Funny to write compared to the old code
- Runs on older versions of NodeJS

Cons:

- A bit slower init time for gulp
- More dependencies

**Comment by Volzy** [comment]
I'd say the known pros trumps the cons, if the init time for Gulp is minimal. What are we talking in terms of init time (ms)?

**Comment by Saturate** [comment]
I have no idea, it's hard to say as it depends on codebase I guess.

We could search the web, or make a little test to see if it's a lot.

**Comment by Volzy** [comment]
I think we should go with the assumption that it's not a lot. It's easier to keep passion about the project if it's fun to build - and ES6 is more fun :)

I do think we should make some tests though to see what the tradeoff is. This doesn't have to block starting up on Babel, but we still want to have an idea what we're up against.

**Comment by Saturate** [comment]
Let's go ES6 then... we can always rewrite in this early stage.

... Or just compile it to ES6-NodeJs / ES5. ;-)
